"""Make contact_id nullable in notifications for system messages

Revision ID: 427d7b2d067d
Revises: fb5837ed6ba9
Create Date: 2025-11-04 12:24:19.673215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427d7b2d067d'
down_revision = 'fb5837ed6ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('contact_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('contact_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
