"""Initial migration with all tables

Revision ID: fb5837ed6ba9
Revises: 
Create Date: 2025-11-04 12:16:31.422303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5837ed6ba9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_clicked_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_days', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('timezone')
        batch_op.drop_column('reminder_days')

    with op.batch_alter_table('plan_guests', schema=None) as batch_op:
        batch_op.drop_column('link_clicked_at')

    # ### end Alembic commands ###
